// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeCeabl58Nu-aa_q-krXQ3feWOU_W0GY',
    appId: '1:628561256399:web:57ae6c3909d7468ae13cba',
    messagingSenderId: '628561256399',
    projectId: 'priticious-51a56',
    authDomain: 'priticious-51a56.firebaseapp.com',
    storageBucket: 'priticious-51a56.firebasestorage.app',
    measurementId: 'G-MJ9JFFPSBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmK3Av33iji9T3SvJnMkE5pr4L2IhIlb4',
    appId: '1:628561256399:android:d1ee9be522faad6be13cba',
    messagingSenderId: '628561256399',
    projectId: 'priticious-51a56',
    storageBucket: 'priticious-51a56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_4xE0X7AycrnhGv-equvwHwsaQTeOIo8',
    appId: '1:628561256399:ios:338d37d91379e0f1e13cba',
    messagingSenderId: '628561256399',
    projectId: 'priticious-51a56',
    storageBucket: 'priticious-51a56.firebasestorage.app',
    iosBundleId: 'com.priticious.priticious',
  );
}
